version: '3'
services:
  sabnzbd:
    image: linuxserver/sabnzbd
    hostname: sabnzbd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.1.12:24224
        tag: docker.sabnzbd
    links:
      - fluentd
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - /opt/sabnzbd/config:/config
      - /mnt/media:/media
    depends_on:
      - fluentd
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"

  plex:
    image: linuxserver/plex
    network_mode: "host"
    hostname: plex
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.1.12:24224
        tag: docker.plex
    volumes:
      - /opt/plex/config:/config
      - /mnt/media:/media
    depends_on:
      - fluentd
    devices:
      - /dev/dri:/dev/dri
    environment:
      - "VERSION=latest"
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"

  sonarr:
    image: linuxserver/sonarr
    hostname: sonarr
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.1.12:24224
        tag: docker.sonarr
    links:
      - sabnzbd
      - plex
      - deluge
      - fluentd
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /opt/sonarr/config:/config
      - /mnt/media:/media
    depends_on:
      - fluentd
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"

  couchpotato:
    image: linuxserver/couchpotato
    hostname: couchpotato
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.1.12:24224
        tag: docker.couchpotato
    links:
      - sabnzbd
      - deluge
      - fluentd
    ports:
      - "5050:5050"
    volumes:
      - /opt/couchpotato/config:/config
      - /mnt/media:/media
    depends_on:
      - fluentd
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"

  deluge:
    image: linuxserver/deluge
    hostname: deluge
    network_mode: "host"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 192.168.1.12:24224
        tag: docker.deluge
    volumes:
      - /opt/deluge/config:/config
      - /mnt/media:/media
    depends_on:
      - fluentd
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"


  plexpy:
    image: linuxserver/plexpy
    ports:
      - "8181:8181"
    depends_on:
      - plex
    volumes:
      - /opt/plexpy/config:/config
      - /opt/plex/config/Library/Application Support/Plex Media Server/Logs:/logs:ro
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"

  pihole:
    image: lplab/pihole
    ports:
      - "53:53/udp"
      - "53:53"
      - "8000:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /opt/pihole/etc/hosts:/etc/hosts
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "ADMIN_PASS=${PIHOLE_PASS}"
      - "SERVER_IP=${SERVER_IP}"

  nginx:
    image: nginx
    depends_on:
      - pihole
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    dns: 192.168.1.12
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"

  fluentd:
    image: fluent/fluentd
    hostname: fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "42185:42185"
      - "42185:42185/udp"
    volumes:
      - /mnt/media/logs:/fluentd/log
      - ./fluentd:/fluentd/etc/
    healthcheck:
      test: ["CMD", "nc", "-vnz", "192.168.1.12", "24224"]
      interval: 10s
      timeout: 3s
      retries: 3
    environment:
      - "FLUENT_UID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"
      - "FLUENTD_CONF=local.conf"
