version: '3'
services:
  sabnzbd:
    image: linuxserver/sabnzbd
    hostname: sabnzbd
    ports:
      - "8080:8080"
      - "9090:9090"
    volumes:
      - /mnt/storage/docker/sabnzbd:/config
      - /mnt/media:/media
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"

  plex:
    image: linuxserver/plex
    network_mode: "host"
    hostname: plex
    volumes:
      - /mnt/storage/docker/plex:/config
      - /mnt/media:/media
      - /tmp/transcode:/transcode
    devices:
      - /dev/dri:/dev/dri
    environment:
      - "VERSION=latest"
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"

  sonarr:
    image: linuxserver/sonarr
    hostname: sonarr
    links:
      - sabnzbd
      - plex
      - deluge
    ports:
      - "8989:8989"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/storage/docker/sonarr:/config
      - /mnt/media:/media
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"

  couchpotato:
    image: linuxserver/couchpotato
    hostname: couchpotato
    links:
      - sabnzbd
      - deluge
    ports:
      - "5050:5050"
    volumes:
      - /mnt/storage/docker/couchpotato:/config
      - /mnt/media:/media
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"

  deluge:
    image: linuxserver/deluge
    hostname: deluge
    network_mode: "host"
    volumes:
      - /mnt/storage/docker/deluge:/config
      - /mnt/media:/media
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"


  plexpy:
    image: linuxserver/plexpy
    ports:
      - "8181:8181"
    depends_on:
      - plex
    volumes:
      - /mnt/storage/docker/plexpy:/config
      - /mnt/storage/docker/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"

  pihole:
    image: lplab/pihole
    ports:
      - "53:53/udp"
      - "53:53"
      - "8000:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /mnt/storage/docker/pihole/etc/hosts:/etc/hosts
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "ADMIN_PASS=${PIHOLE_PASS}"
      - "SERVER_IP=${SERVER_IP}"

  nginx:
    image: nginx
    depends_on:
      - pihole
    links:
      - plex
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    dns:
      - 192.168.1.12
    dns_search:
      - shift.com
    environment:
      - "PGID=1000"
      - "PUID=1000"
      - "TZ=America/Chicago"
